In [3]:
import numpy as np
import math

In [88]:
m = 250
n = 450
vol = 2900
sim = 3000

hug = set()
count = 0

for _ in range(sim):
    for _ in range(vol):
        student = np.random.randint(1, 451)
        if student <= m:
            hug.add(student)
    if len(hug) == m:
        count += 1
    hug = set()

print("times of covering all sad students: " + str(count) + " out of " + str(sim) + ". Probability is {}".format(count * 1.0 / sim))

times of covering all sad students: 1985 out of 3000. Probability is 0.6616666666666666


In [77]:
print("times of covering all sad students: " + str(count) + " out of " + str(sim) + ". Probability is {}".format(count * 1.0 / sim))

times of covering all sad students: 7192 out of 10000. Probability is 0.7192


times of covering all sad students: 7192 out of 10000. Probability is 0.7192